[settings]
screenchange-reload = true

[bar/top]
monitor = eDP-1
bottom = true
font-0="FiraCode Nerd Font:pixelsize=8;2"
font-1="Symbols Nerd Font:pixelsize=12;2"
background=#000
border-size = 4
border-color=#000
fixed-center = true
width = 100%
height=16

modules-left=i3
modules-right=spotify battery pulse wlan date


separator = 
spacing = 0
dim-value = 1.0
line-size=2

[bar/hdmi]
monitor = HDMI-1
bottom = true
font-0="FiraCode Nerd Font:pixelsize=8;2"
font-1="Symbols Nerd Font:pixelsize=12;2"
background=#000
border-size = 4
border-color=#000
fixed-center = true
width = 100%
height=16

modules-left=i3
modules-right=spotify battery pulse wlan date

separator = 
spacing = 0
dim-value = 1.0
line-size=2


[module/bspwm]
type=internal/bspwm
format= <label-state> 
format-background = #000000

pin-workspaces=true

enable-click = true
index-sort=true
wrapping-scroll=true
enable-scroll=true

label-mode=" %mode%"
label-mode-background=#000000

label-focused=%name%
label-focused-foreground= #fff
label-focused-underline=#fff
label-focused-background=#282828
label-focused-padding=2

label-occupied=%name%
label-occupied-foreground=#ffffff
label-occupied-underline=#555
label-occupied-background=#000000
label-occupied-padding=2

label-unfocused=%name%
label-unfocused-foreground = #262626
label-unfocused-background= #000000
label-unfocused-padding=2

label-empty=%name%
label-empty-padding=2
label-empty-foreground = #282828
label-empty-background= #000000

label-urgent = %name%

[module/i3]
type = internal/i3

format= <label-state>
format-background = #000000

pin-workspaces=true

enable-click = true
index-sort=true
wrapping-scroll=true
enable-scroll=true

label-mode=" %mode%"
label-mode-background=#000000

label-focused=%name%
label-focused-foreground= #fff
label-focused-underline=#fff
label-focused-background=#282828
label-focused-padding=1

label-occupied=%name%
label-occupied-foreground=#ffffff
label-occupied-underline=#555
label-occupied-background=#000000
label-occupied-padding=1

label-unfocused=%name%
label-unfocused-foreground = #262626
label-unfocused-background= #000000
label-unfocused-padding=1

label-empty=%name%
label-empty-padding=1
label-empty-foreground = #282828
label-empty-background= #000000

label-urgent = %name%

[module/battery]
type = custom/script
exec = battery
format = <label>
format-background=#000
format-foreground=#fff
label=   %output%%
format-padding=1

[module/title]
type= internal/xwindow
format =  <label>
format-padding=1
format-background=#ffffff
format-foreground=#000000
label = %title%
label-background=#000
label-foreground=#fff
label-maxlen=30
label-padding=3

[module/pulse]
type= internal/pulseaudio
use-ui-max=false

interval = 5

format-volume = <ramp-volume> <label-volume> 
bar-volume-width=10
format-volume-padding = 1
format-volume-background=#000
label-muted-foreground = #66
label-muted-background=#000

label-muted = 󰝟 muted
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 󰕾

;ramp-volume-padding=1
;label-muted-padding=1
;ramp-headphones-padding=1

[module/date]
type = internal/date

interval = 1.0

time = %H:%M
date = "%y %b %d"

format =   <label>
format-background=#000
label=  %date%, %time%
label-background=#000
format-padding=1

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-connected-background = #000
format-disconnected = ""
format-disconnected-background= #000

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected =   %essid%
label-connected-padding=1

[module/mpd]
type=internal/mpd
label-song=  - %title%
format-online = <icon-prev> <icon-play> <icon-pause> <icon-next> <bar-progress> <label-song>
format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}
icon-play = 
icon-next = 󰒭
icon-prev = 󰒮
icon-pause = 
icon-stop = 
bar-progress-width = 10
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-empty = ─
label-offline = mpd is offline
label-song-background=#282828
label-song-padding=1
format-playing-background=#282828
format-paused-background=#282828
format-stopped-background=#282828
format-playing-padding=1
format-paused-padding=1
format-stopped-padding=1

[module/spotify]
type = custom/script
interval = 1
format-prefix = " "
format = <label>
exec = python ~/.config/polybar/spotify_status.py -f '{artist}: {song}'
format-padding = 1
format-background = #1db954
format-foreground = #000000
;format-underline = #1db954
;control players (optional)
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous
